// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RCPylonRaceManagerWithSQLServer.Data;

namespace RCPylonRaceManagerWithSQLServer.Migrations
{
    [DbContext(typeof(PylonDbContext))]
    [Migration("20210309232034_initialEntities")]
    partial class initialEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RCPylonRaceManagerWithSQLServer.Model.Entities.Heat", b =>
                {
                    b.Property<int>("RaceDayId")
                        .HasColumnType("int");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.HasKey("RaceDayId", "RoundNumber");

                    b.ToTable("Heat");
                });

            modelBuilder.Entity("RCPylonRaceManagerWithSQLServer.Model.Entities.RaceDayPilot", b =>
                {
                    b.Property<int>("SeasonPilotId")
                        .HasColumnType("int");

                    b.Property<int>("RaceDayId")
                        .HasColumnType("int");

                    b.Property<bool>("HasPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOTS")
                        .HasColumnType("bit");

                    b.HasKey("SeasonPilotId", "RaceDayId");

                    b.ToTable("RaceDayPilot");
                });

            modelBuilder.Entity("RCPylonRaceManagerWithSQLServer.Model.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Year = 2021
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
